spring.application.name=HousekeepingWorkflowManagementSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/housekeeping
spring.datasource.username=postgres
spring.datasource.password=likhitUsingPostgre
